version: '3.7'
services:
  api:
    build:
      # Read Makefile to understand why we want to build from the top-level "." context.
      context: .
      dockerfile: dockerfile/api/Dockerfile
    image: api-server:latest
    command: [
      "/app/api/build/server",
      "--config=/app/api/config/prod.yaml"
    ]
    ports:
      - "20005:20005"
  bastion:
    build:
      # Read Makefile to understand why we want to build from the top-level "." context.
      context: .
      dockerfile: dockerfile/bastion/Dockerfile
    image: bastion:latest