apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: edge
  name: bastion
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: bastion
        env:
          - name: SERVER_ENV
            value: "prod"
        resources:
          requests:
            cpu: "300m"
            memory: "800Mi"
          limits:
            cpu: "500m"
            memory: "1000Mi"