apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- service.yaml
- deployment.yaml
images:
- name: 243963068353.dkr.ecr.us-west-2.amazonaws.com/api-server
  newName: 243963068353.dkr.ecr.us-west-2.amazonaws.com/api-server
  newTag: latest
